modLoader="javafml"
loaderVersion="[40,)"
license="MIT"

[[mods]]
modId="dtafc"
version="1.0.0"
displayName="Dynamic Trees AFC"
authors="TDino"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.dtafc]]
modId="tfc"
mandatory=true
versionRange="[3.2.20,)"
ordering="AFTER"
side="BOTH"

[[dependencies.dtafc]]
modId="afc"
mandatory=true
versionRange="[1.0.20,)"
ordering="AFTER"
side="BOTH"

[[dependencies.dtafc]]
modId="dynamictrees"
mandatory=true
versionRange="[1.4.9,)"
ordering="AFTER"
side="BOTH"

[[dependencies.dtafc]]
modId="dynamictreesplus"
mandatory=true
versionRange="[1.0.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.dtafc]]
modId="dttfc"
mandatory=true
versionRange="[2.0.2,)"
ordering="AFTER"
side="BOTH"

[[dependencies.dtafc]]
modId="dtaddon_lib"
mandatory=true
versionRange="[0.1.0-BETA3,)"
ordering="AFTER"
side="BOTH"

[[dependencies.dtafc]]
modId="create"
mandatory=false
versionRange="[0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.dtafc]]
modId="immersiveengineering"
mandatory=false
versionRange="[0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.dtafc]]
modId="tfc_debark"
mandatory=false
versionRange="[0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.dtafc]]
modId="tfc_lumberjack"
mandatory=false
versionRange="[0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.dtafc]]
modId="lychee"
mandatory=false
versionRange="[0,)"
ordering="AFTER"
side="BOTH"
